from django.shortcuts import render
from django.shortcuts import redirect

from .models import MainStockCategoryModel, MainStockGroupModel, StockCategoryModel, StockGroupModel

# Create your views here.

def base(request):
    return render(request, 'base.html')

def index(request):
    return render(request, 'home.html')

def group(request):
    return render(request, 'groups.html')

def branch(request):
    return render(request, 'branch.html')

def ledger(request):
    return render(request, 'ledger.html')

def primary(request):
    return render(request, 'primarycost.html')

def costcat(request):
    return render(request, 'costcat.html')

def costcentr(request):
    return render(request, 'costcentr.html')

def voucher(request):
    return render(request, 'voucher.html')

def vouchpage(request):
    return render(request, 'vouchpage.html')


#maingroupsview

def maingroupsview(request):
    grps=MainStockGroupModel.objects.all()
    context={
        'grps':grps,
        } 
    return render(request,'maingroups.html',context)
#maincategory

def maincategoryview(request):
    cat=MainStockCategoryModel.objects.all()
    context={
        'cat':cat,
        } 
    return render(request,'maincategory.html',context)


# Generated by Django 4.0.6 on 2022-08-
#categorysallview
def categorysallview(request):
    grps=MainStockGroupModel.objects.all()
    context={
        'grps':grps,
        } 
    return render(request,'groupsall.html',context)

#mcreatecategory

def creategroupsview(request):
    grps=StockGroupModel.objects.all()
    context={
        'grps':grps,
        } 
    return render(request, 'creategroups.html',context)    

#createcategoryview

def createcategoryview(request):
    cat=StockCategoryModel.objects.all()
    context={
        'cat':cat,
        } 
    return render(request, 'createcategory.html',context) 


#savestockgroups

def savestockgroup(request):
    if request.method=='POST':
        gname=request.POST['name']
        s=StockGroupModel(group_name=gname)
        s.save()
        abr=request.POST['alias']
        grp=request.POST.get('u')
        gp=StockGroupModel.objects.get(group_name=grp)
        q=request.POST.get('qty')
        gst=request.POST.get('gst')
        sg=MainStockGroupModel(gname=gname,alias=abr,quantities=q,under=grp,group=gp ,gst=gst)
        sg.save()
        return redirect('maingroupsview')

#savestockgroup

def savestockcategory(request):
    if request.method=='POST':
        catname=request.POST['name']
        s=StockCategoryModel(cat_name=catname)
        s.save()
        abr=request.POST['alias']
        cat=request.POST.get('u')
        c=StockCategoryModel.objects.get(cat_name=cat)
        q=request.POST.get('qty')
        sc=MainStockCategoryModel(cname=catname,alias=abr,quantities=q,under=cat,category=c)
        sc.save()
        return redirect('maincategoryview')



# Generated by Django 4.0.6 on 2022-08-16 08:54
def createseconomygroup(request):
    gps =MainStockGroupModel.objects.all()
    context = {
        'gps':gps
    }
    return redirect('maingroupsview' , context) 