# Generated by Django 4.0.6 on 2022-08-12 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_stockgroupmodel_mainstockgroupmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstockgroupmodel',
            name='group',
        ),
        migrations.AlterField(
            model_name='mainstockgroupmodel',
            name='under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockgroupmodel'),
        ),
    ]
