# Generated by Django 4.0.6 on 2022-08-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_mainstockgroupmodel_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainstockgroupmodel',
            old_name='name',
            new_name='gname',
        ),
    ]
