# Generated by Django 4.0.6 on 2022-08-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_name_mainstockgroupmodel_gname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageinganalysismodel',
            name='value',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='ageinganalysismodel',
            name='pname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.mainstockgroupmodel'),
        ),
        migrations.AlterField(
            model_name='mainstockgroupmodel',
            name='alias',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='mainstockgroupmodel',
            name='gname',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='mainstockgroupmodel',
            name='quantities',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
