# Generated by Django 4.0.6 on 2022-08-12 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_ageinganalysismodel_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ageinganalysismodel',
            old_name='value',
            new_name='Values',
        ),
    ]
