# Generated by Django 4.0.6 on 2022-08-12 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_remove_ageinganalysismodel_values_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageinganalysismodel',
            name='pname',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
