# Generated by Django 4.0.6 on 2022-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_ageinganalysismodel_pname'),
    ]

    operations = [
        migrations.AddField(
            model_name='ageinganalysismodel',
            name='value',
            field=models.IntegerField(null=True),
        ),
    ]
