# Generated by Django 4.0.6 on 2022-08-12 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_ageinganalysismodel_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ageinganalysismodel',
            name='pname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.mainstockgroupmodel'),
        ),
    ]
