# Generated by Django 4.0.6 on 2022-08-15 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_remove_mainstockcategorymodel_quantities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainstockcategorymodel',
            name='under',
            field=models.ForeignKey(default='primary', null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategorymodel'),
        ),
    ]
