# Generated by Django 4.0.6 on 2022-08-15 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_mainstockcategorymodel_under'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstockgroupmodel',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockgroupmodel'),
        ),
        migrations.AlterField(
            model_name='mainstockcategorymodel',
            name='under',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategorymodel'),
        ),
        migrations.AlterField(
            model_name='mainstockgroupmodel',
            name='under',
            field=models.CharField(max_length=225, null=True, unique=True),
        ),
    ]
