# Generated by Django 4.0.6 on 2022-08-16 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_mainstockgroupmodel_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstockcategorymodel',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategorymodel'),
        ),
        migrations.AlterField(
            model_name='mainstockcategorymodel',
            name='under',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
