# Generated by Django 4.0.6 on 2022-08-17 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0020_mainstockcategorymodel_quantities'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateStockCateg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under', models.CharField(max_length=50)),
                ('quantities', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreateStockGrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under', models.CharField(max_length=100, null=True)),
                ('quantities', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stockcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='StockGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grp_name', models.CharField(max_length=70)),
            ],
        ),
        migrations.RemoveField(
            model_name='mainstockgroupmodel',
            name='group',
        ),
        migrations.DeleteModel(
            name='MainStockCategoryModel',
        ),
        migrations.DeleteModel(
            name='MainStockGroupModel',
        ),
        migrations.DeleteModel(
            name='StockCategoryModel',
        ),
        migrations.DeleteModel(
            name='StockGroupModel',
        ),
        migrations.AddField(
            model_name='createstockgrp',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockgroup'),
        ),
        migrations.AddField(
            model_name='createstockcateg',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.stockcategory'),
        ),
    ]
