# Generated by Django 4.0.6 on 2022-08-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0021_createstockcateg_createstockgrp_stockcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createstockgrp',
            name='gst',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
