# Generated by Django 4.0.6 on 2022-08-18 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0022_createstockgrp_gst'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stockcategory',
            new_name='CreateStockcategoryModel',
        ),
        migrations.RenameModel(
            old_name='StockGroup',
            new_name='CreateStockGroupModel',
        ),
        migrations.RenameModel(
            old_name='CreateStockCateg',
            new_name='MainStockCategoryModel',
        ),
        migrations.RenameModel(
            old_name='CreateStockGrp',
            new_name='MainStockGroupModel',
        ),
    ]
