# Generated by Django 4.0.6 on 2022-08-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0023_rename_stockcategory_createstockcategorymodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstockcategorymodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='mainstockgroupmodel',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
