# Generated by Django 4.0.6 on 2022-08-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0024_mainstockcategorymodel_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainstockcategorymodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mainstockgroupmodel',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
