# Generated by Django 4.0.6 on 2022-08-29 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0025_mainstockcategorymodel_updated_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainstockcategorymodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='mainstockcategorymodel',
            name='updated_on',
        ),
        migrations.RemoveField(
            model_name='mainstockgroupmodel',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='mainstockgroupmodel',
            name='updated_on',
        ),
    ]
