# Generated by Django 4.1 on 2022-09-09 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0027_mainstockgroupmodel_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paritculars', models.CharField(max_length=100, null=True)),
                ('expirydate', models.DateTimeField()),
                ('quantity', models.IntegerField(null=True)),
                ('value', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.createstockcategorymodel')),
                ('group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.createstockgroupmodel')),
            ],
        ),
    ]
