# Generated by Django 4.1 on 2022-09-14 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0028_ageingmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ageingmodel",
            name="expirydate",
        ),
    ]
